import {fieldText,t} from '@/lib/i18n';
import {Header,Footer} from '@/components/studio-chrome';
import {RenderImage} from '@/components/render-image';
import {getPublicContent} from '@/lib/content-store';
import {pageMetadata} from '@/lib/seo';
export const metadata=pageMetadata('Services','Exterior, interior, masterplan, façade, product and outdoor-living visualization services by Mirzazada Studio.','/services');
const audiences=['Architecture studios and developers','Interior designers and hospitality teams','Pergola, glazing and outdoor-living manufacturers','Design teams presenting a space or product in motion','Manufacturers and design studios','Developers and landscape architects','Architects and façade development teams'];
const deliverables=['Exterior perspectives, material studies and presentation images.','Interior perspectives, lighting studies and material-focused views.','Pergolas and glass systems in context, product views and technical details.','Animated perspectives and AI-assisted visual presentations, scoped to the project.','Detailed 3D models and presentation-ready product assets.','Master views, aerial perspectives and landscape visualization.','Façade concepts, renewal studies and material alternatives.'];
export default function ServicesPage(){const {data:{settings}}=getPublicContent();return <><Header/><main id="main"><section className="section services-intro"><p className="eyebrow">{t("MIRZAZADA STUDIO / SERVICES")}</p><h1>{t("Your design.")}<br/><span>{t("Clearly communicated.")}</span></h1><p>{t("From the scale of a neighborhood to the detail of a louver mechanism. A considered visual approach, shaped around your project.")}</p></section><div className="services-detail-list">{settings.services.map((service,i)=><section key={i} id={'service-'+(i+1)} className="service-detail"><div><RenderImage src={service.image} alt={fieldText(service.title,'service:'+i+':title')} loading="lazy"/></div><div><p className="eyebrow">0{i+1} / {fieldText(service.tag,'service:'+i+':tag')}</p><h2>{fieldText(service.title,'service:'+i+':title')}</h2><p>{fieldText(service.text,'service:'+i+':text')}</p><dl><dt>{t("For")}</dt><dd>{fieldText(service.audience||audiences[i]||'Architecture and design teams','service:'+i+':audience')}</dd><dt>{t("Deliverables")}</dt><dd>{fieldText(service.deliverables||deliverables[i]||'A tailored set of project visuals.','service:'+i+':deliverables')}</dd></dl><a className="text-link" href="/contact">{t("Discuss your project ↗")}</a></div></section>)}</div></main><Footer/></>;}
