import {studioFetch} from '@/web/api';
'use client';
import {useEffect,useState} from 'react';
import {NativeSelect,NativeSelectOption} from './ui/native-select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction} from './ui/alert-dialog';
import {upgradeCatalog} from '@/lib/catalog-upgrade';
import type {SiteContent} from '@/lib/content-types';
import type {MediaInfo} from '@/lib/media-types';
type Inquiry={id:string;name:string;email:string;company:string;project_type:string;deadline:string;message:string;status:string;notification:string;created_at:string;attribution:string};
export function AdminOperations({restore}:{restore:(data:SiteContent)=>void}){
 const [inquiries,setInquiries]=useState<Inquiry[]>([]),[assets,setAssets]=useState<MediaInfo[]>([]),[versions,setVersions]=useState<{revision:number;created_at:string}[]>([]),[error,setError]=useState(''),[candidate,setCandidate]=useState<SiteContent|null>(null);
 async function load(){setError('');try{const requests=await Promise.all(['/api/admin/inquiries','/api/admin/assets','/api/admin/backup?revision=list'].map(async url=>{const response=await studioFetch(url);if(!response.ok)throw Error('Məlumat yüklənmədi.');return await response.json() as {items:unknown[]}}));setInquiries(requests[0].items as Inquiry[]);setAssets(requests[1].items as MediaInfo[]);setVersions(requests[2].items as {revision:number;created_at:string}[]);}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[]);
 return <section className="admin-home-editor"><div className="admin-section-heading"><h2>Müraciətlər və ehtiyat nüsxələr</h2><button className="outline-button" onClick={load}>Yenilə ↻</button></div>{error&&<p role="alert" className="admin-error">{error}</p>}<p className="admin-banner">Poçt bildirişi hələ qoşulmayıb. Saytdan göndərilən bütün müraciətlər bu qutuda saxlanır.</p><div className="admin-inquiries">{!inquiries.length&&<p className="admin-empty">Hələ müraciət yoxdur.</p>}{inquiries.map(item=><article key={item.id}><div className="admin-section-heading"><h3>{item.name}</h3><small>{new Date(item.created_at).toLocaleString('az-AZ')}</small></div><a href={'mailto:'+item.email}>{item.email}</a><p>{[item.company,item.project_type,item.deadline].filter(Boolean).join(' · ')}</p><p className="inquiry-message">{item.message}</p><label>Status<NativeSelect value={item.status} onChange={async event=>{const status=event.target.value;try{const response=await studioFetch('/api/admin/inquiries',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,status})});if(!response.ok)throw Error('Status saxlanmadı.');setInquiries(list=>list.map(row=>row.id===item.id?{...row,status}:row));}catch(e){setError((e as Error).message)}}}>{[['new','Yeni'],['reviewing','Baxılır'],['replied','Cavablandı'],['closed','Bağlandı'],['spam','Spam']].map(([value,label])=><NativeSelectOption key={value} value={value}>{label}</NativeSelectOption>)}</NativeSelect></label>{item.attribution!=='{}'&&<details><summary>Müraciət mənbəyi</summary><dl>{Object.entries(JSON.parse(item.attribution) as Record<string,string>).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></details>}</article>)}</div>
 <h2 className="admin-operation-heading">Ehtiyat nüsxələr</h2><p className="admin-hint">Hər saxlamadan əvvəl əvvəlki məzmun avtomatik qorunur. Son 30 versiyanı yükləyə və bərpa edə bilərsiniz. JSON ixracında məzmun, müraciətlər və fayl siyahısı var; orijinal fayllar ayrıca arxivdə saxlanır.</p><div className="admin-editor-actions"><a className="dark-button" href="/api/admin/backup" download>Hamısını JSON kimi yüklə ↓</a><label className="admin-upload">JSON-dan bərpa et<input type="file" accept="application/json,.json" onChange={async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(file.size>8*1024*1024)throw Error('Fayl çox böyükdür.');const backup=JSON.parse(await file.text());if(backup.format!=='mirzazada-studio-backup-v1'||!Array.isArray(backup.content?.projects))throw Error('Studio ehtiyat nüsxəsi seçin.');setCandidate(upgradeCatalog(backup.content));}catch(e){setError((e as Error).message)}}}/></label></div><div className="admin-backup-list">{versions.map(version=><a key={version.revision} href={'/api/admin/backup?revision='+version.revision} download>Versiya {version.revision} · {new Date(version.created_at).toLocaleString('az-AZ')} ↓</a>)}</div>
 <h2 className="admin-operation-heading">Orijinal render arxivi</h2><p className="admin-hint">Yeni yüklənən orijinallar özəldir. Eyni fayl yenidən yüklənəndə hash ilə tanınır. Hazırkı köhnə portfolio fayllarının ayrıca miqrasiya hesabatı hazırlanır.</p><div className="admin-asset-list">{assets.map(asset=><a key={asset.id} href={'/api/admin/assets/'+asset.id} download><span>{asset.name}<small>{asset.width} × {asset.height} · {(asset.size/1024/1024).toFixed(1)} MB</small></span><span>Orijinal ↓</span></a>)}</div>
 <AlertDialog open={!!candidate} onOpenChange={open=>{if(!open)setCandidate(null)}}><AlertDialogContent><AlertDialogTitle>Məzmun bu nüsxədən bərpa edilsin?</AlertDialogTitle><AlertDialogDescription>Əvvəlcə redaktora yüklənəcək. Sayta tətbiq etmək üçün yuxarıdan saxlayın. Orijinal fayllar və müraciətlər silinmir.</AlertDialogDescription><AlertDialogCancel>Ləğv et</AlertDialogCancel><AlertDialogAction onClick={()=>{if(candidate)restore(candidate);setCandidate(null)}}>Redaktora yüklə</AlertDialogAction></AlertDialogContent></AlertDialog></section>;
}
