'use client';
import {useState} from 'react';
import type {Project} from '@/lib/projects';
import type {SiteContent} from '@/lib/content-types';
import {newBlock,type ProjectBlock} from '@/lib/project-blocks';
import {legacyBlocks,ProjectStory} from './project-story';
import {RenderImage} from './render-image';
import {NativeSelect,NativeSelectOption} from './ui/native-select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction} from './ui/alert-dialog';
type Props={project:Project;edit:(fn:(project:Project)=>void)=>void};
export function ProjectDetailsEditor({project:p,edit}:Props){return <><div className="admin-fields"><label>Status<NativeSelect value={p.status||'published'} onChange={e=>edit(project=>{project.status=e.target.value as Project['status']})}><NativeSelectOption value="draft">Qaralama</NativeSelectOption><NativeSelectOption value="published">Yayımda</NativeSelectOption><NativeSelectOption value="archived">Arxiv</NativeSelectOption></NativeSelect></label><label>Paylaşma icazəsi<NativeSelect value={p.displayPermission||'unreviewed'} onChange={e=>edit(project=>{project.displayPermission=e.target.value as Project['displayPermission'];if(e.target.value==='confidential')project.status='draft'})}><NativeSelectOption value="unreviewed">Yoxlanılacaq</NativeSelectOption><NativeSelectOption value="confirmed">Təsdiqlənib</NativeSelectOption><NativeSelectOption value="confidential">Məxfi — ictimai göstərmə</NativeSelectOption></NativeSelect></label>{(['location','year','client','credit','seoTitle','seoDescription'] as const).map((key,i)=><label key={key}>{['Məkan','İl','Müştəri','Memar / dizayner krediti','Axtarış başlığı','Axtarış təsviri'][i]}<input value={p[key]||''} maxLength={key==='year'?4:key==='seoTitle'?150:key==='seoDescription'?320:key==='credit'?300:200} onChange={e=>edit(project=>{project[key]=e.target.value})}/></label>)}<label className="full">Göstərdiyiniz xidmətlər — hər sətirdə bir xidmət<textarea rows={3} value={(p.services||[]).join('\n')} onChange={e=>edit(project=>{project.services=e.target.value.split('\n')})}/></label></div><h3>Örtük fokusu</h3><div className="admin-frame-controls">{(['x','y','zoom'] as const).map(key=><label key={key}>{key==='zoom'?'Zoom':key.toUpperCase()+' mövqeyi'}<input type="range" min={key==='zoom'?1:0} max={key==='zoom'?3:100} step={key==='zoom'?.05:1} value={p.coverFrame?.[key]??(key==='zoom'?1:50)} onChange={e=>edit(project=>{project.coverFrame={x:50,y:50,zoom:1,...project.coverFrame,[key]:Number(e.target.value)}})}/></label>)}</div>{(p.coverImage||p.images[0])&&<div className="admin-cover-focus"><RenderImage src={p.coverImage||p.images[0]||''} alt="Örtük önbaxışı" style={{objectPosition:`${p.coverFrame?.x??50}% ${p.coverFrame?.y??50}%`,transform:`scale(${p.coverFrame?.zoom??1})`,transformOrigin:`${p.coverFrame?.x??50}% ${p.coverFrame?.y??50}%`}}/></div>}</>;}
export function BlockEditor({project:p,edit}:Props){
 const [dragged,setDragged]=useState<number|null>(null),[remove,setRemove]=useState<number|null>(null),[preview,setPreview]=useState(false),[mobile,setMobile]=useState(false);
 const blocks=p.blocks??legacyBlocks(p);
 function change(fn:(blocks:ProjectBlock[])=>void){edit(project=>{project.blocks=structuredClone(project.blocks??legacyBlocks(project));fn(project.blocks)})}
 function move(from:number,to:number){if(to<0||to>=blocks.length)return;change(list=>{const [block]=list.splice(from,1);list.splice(to,0,block)})}
 function add(type:ProjectBlock['type']){change(list=>{const block=newBlock(type,p.images[0]||'');if(type==='columns')block.images.push({...structuredClone(block.images[0]),src:p.images[1]||p.images[0]||''});list.push(block)})}
 return <section className="admin-block-editor"><div className="admin-section-heading"><div><h3>Layihə səhifəsinin blokları</h3><p>Mətn, render və videoları bir hekayə kimi düzün. Şəkillərin nisbəti qorunur.</p></div><button className="outline-button" onClick={()=>setPreview(true)}>Önbaxış ↗</button></div><div className="block-add-menu">{([['image','Şəkil'],['columns','2/3 sütun'],['heading','Başlıq'],['text','Mətn'],['video','Video'],['spacer','Boşluq']] as const).map(([type,label])=><button key={type} onClick={()=>add(type)}>+ {label}</button>)}</div>
 {blocks.map((block,i)=><article key={block.id} className="admin-block" onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect='move'}} onDrop={event=>{event.preventDefault();if(dragged!==null)move(dragged,i);setDragged(null)}}><div className="admin-block-toolbar"><span draggable onDragStart={event=>{setDragged(i);event.dataTransfer.setData('text/plain',block.id)}} onDragEnd={()=>setDragged(null)} className="drag-handle" aria-hidden="true">⠿</span><strong>{i+1}. {block.type}</strong><button disabled={i===0} onClick={()=>move(i,i-1)} aria-label="Bloku əvvələ çək">↑</button><button disabled={i===blocks.length-1} onClick={()=>move(i,i+1)} aria-label="Bloku sona çək">↓</button><button onClick={()=>change(list=>{const copy=structuredClone(list[i]);copy.id=crypto.randomUUID();copy.createdAt=copy.updatedAt=new Date().toISOString();list.splice(i+1,0,copy)})}>Surət</button><button onClick={()=>setRemove(i)}>Çıxar</button></div>
 {['image','columns'].includes(block.type)&&<><label>Yerləşmə<NativeSelect value={block.layout} onChange={e=>change(list=>{list[i].layout=e.target.value as ProjectBlock['layout']})}><NativeSelectOption value="full">Tam en</NativeSelectOption><NativeSelectOption value="contained">Mərkəzdə, məhdud en</NativeSelectOption></NativeSelect></label>{block.type==='columns'&&<label>Sütun sayı<NativeSelect value={block.images.length} onChange={e=>change(list=>{const count=Number(e.target.value);while(list[i].images.length<count)list[i].images.push({src:p.images[0]||'',alt:'',caption:'',credit:'',frame:{x:50,y:50,zoom:1}});list[i].images=list[i].images.slice(0,count)})}><NativeSelectOption value={2}>2</NativeSelectOption><NativeSelectOption value={3}>3</NativeSelectOption></NativeSelect></label>}<div className="admin-block-images">{block.images.map((item,j)=><div key={j}>{item.src&&<RenderImage src={item.src} alt={item.alt}/>}<label>Renderi seç / əvəz et<NativeSelect value={item.src} onChange={e=>change(list=>{list[i].images[j].src=e.target.value})}><NativeSelectOption value="">Render seçin</NativeSelectOption>{Array.from(new Set([item.src,...p.images].filter(Boolean))).map(src=><NativeSelectOption key={src} value={src}>{src.split('/').pop()}</NativeSelectOption>)}</NativeSelect></label>{(['alt','caption','credit'] as const).map((key,k)=><label key={key}>{['Alt mətn','Şəkil açıqlaması','Kredit'][k]}<input value={item[key]} onChange={e=>change(list=>{list[i].images[j][key]=e.target.value})}/></label>)}<div className="admin-frame-controls">{(['x','y','zoom'] as const).map(key=><label key={key}>{key}<input type="range" min={key==='zoom'?1:0} max={key==='zoom'?3:100} step={key==='zoom'?.05:1} value={item.frame[key]} onChange={e=>change(list=>{list[i].images[j].frame[key]=Number(e.target.value)})}/></label>)}</div></div>)}</div></>}
 {['text','heading'].includes(block.type)&&<label>{block.type==='heading'?'Başlıq':'Mətn — abzasları boş sətirlə ayırın'}<textarea rows={block.type==='heading'?2:5} value={block.text} onChange={e=>change(list=>{list[i].text=e.target.value})}/></label>}
 {block.type==='heading'&&<label>Səviyyə<NativeSelect value={block.level} onChange={e=>change(list=>{list[i].level=e.target.value as 'h2'|'h3'})}><NativeSelectOption value="h2">Bölmə başlığı</NativeSelectOption><NativeSelectOption value="h3">Alt başlıq</NativeSelectOption></NativeSelect></label>}
 {block.type==='video'&&<><label>YouTube / Vimeo ünvanı<input value={block.url} onChange={e=>change(list=>{list[i].url=e.target.value})}/></label><label>Video başlığı<input value={block.text} onChange={e=>change(list=>{list[i].text=e.target.value})}/></label><label>Poster<NativeSelect value={block.poster} onChange={e=>change(list=>{list[i].poster=e.target.value})}><NativeSelectOption value="">Postersiz</NativeSelectOption>{p.images.map(src=><NativeSelectOption key={src} value={src}>{src.split('/').pop()}</NativeSelectOption>)}</NativeSelect></label></>}
 {block.type==='spacer'&&<label>Boşluq<NativeSelect value={block.spacing} onChange={e=>change(list=>{list[i].spacing=e.target.value as ProjectBlock['spacing']})}><NativeSelectOption value="small">Kiçik</NativeSelectOption><NativeSelectOption value="medium">Orta</NativeSelectOption><NativeSelectOption value="large">Böyük</NativeSelectOption></NativeSelect></label>}
 </article>)}
 <AlertDialog open={remove!==null} onOpenChange={open=>{if(!open)setRemove(null)}}><AlertDialogContent><AlertDialogTitle>Blok çıxarılsın?</AlertDialogTitle><AlertDialogDescription>Render faylı saxlanacaq. Əvvəlki saxlanmış məzmun ehtiyat nüsxədə qalır.</AlertDialogDescription><AlertDialogCancel>Ləğv et</AlertDialogCancel><AlertDialogAction onClick={()=>{if(remove!==null)change(list=>{list.splice(remove,1)});setRemove(null)}}>Bloku çıxar</AlertDialogAction></AlertDialogContent></AlertDialog>
 <Dialog open={preview} onOpenChange={setPreview}><DialogContent className="project-preview-dialog"><DialogTitle>{p.title} — saxlanmamış önbaxış</DialogTitle><DialogDescription>Bu baxış yalnız admin üçündür; yadda saxlamadan da düzəlişləri görə bilərsiniz.</DialogDescription><div className="preview-switch"><button aria-pressed={!mobile} onClick={()=>setMobile(false)}>Masaüstü</button><button aria-pressed={mobile} onClick={()=>setMobile(true)}>Mobil</button></div><div className={mobile?'project-preview-frame mobile':'project-preview-frame'}><ProjectStory project={p}/></div></DialogContent></Dialog>
 </section>;
}
