import {studioFetch} from '@/web/api';
'use client';
import {BlockEditor,ProjectDetailsEditor} from './admin-project-details';
import {AdminAnimation} from './admin-animation';
import {AdminOperations} from './admin-operations';
import {uploadStudioAsset} from '@/lib/upload-client';
import {CollectionEditor,ProfileEditor,JournalEditor,ReviewEditor} from './admin-editorial';
import {useEffect,useState,type FormEvent} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {ContentProvider} from './content-provider';
import {RenderImage} from './render-image';
import type {ContentRecord,SiteContent} from '@/lib/content-types';
import {projectCategories,projectTopics,hasCategory,type Project,type Category} from '@/lib/projects';

type Auth={authenticated:boolean;owner:boolean;configured:boolean;username?:string};
async function api<T=Record<string,unknown>>(path:string,options?:RequestInit){
 const response=await studioFetch(path,{...options,headers:{...(options?.body&&typeof options.body==='string'?{'Content-Type':'application/json'}:{}),...options?.headers}});
 const data=await response.json() as T & {error?:string};if(!response.ok)throw Error(data.error||'Əməliyyat alınmadı.');return data;
}
export function AdminPanel(){
 const [auth,setAuth]=useState<Auth|null>(null),[record,setRecord]=useState<ContentRecord|null>(null);
 const [selected,setSelected]=useState(0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [confirm,setConfirm]=useState(false);
 const [search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState('all'),[dragged,setDragged]=useState<number|null>(null),[removeTarget,setRemoveTarget]=useState<string|null>(null),[progress,setProgress]=useState(0);
 async function load(){
  setError('');try{const a=await api<Auth>('/api/admin/auth');setAuth(a);if(a.authenticated){setRecord(await api<ContentRecord>('/api/admin/content'));setDirty(false);}}catch(e){setError((e as Error).message);}
 }
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 function edit(fn:(data:SiteContent)=>void){setRecord(r=>{if(!r)return r;const data=structuredClone(r.data);fn(data);for(const c of data.collections){if(c.featuredProject&&!data.projects.some(p=>p.slug===c.featuredProject&&hasCategory(p,c.category)))c.featuredProject='';}for(const post of data.journal){if(post.projectSlug&&!data.projects.some(p=>p.slug===post.projectSlug))post.projectSlug='';}return {...r,data}});setDirty(true);setMessage('');setError('');}
 function projectEdit(key:keyof Project,value:unknown){edit(d=>{const p=d.projects[selected];if(key==='slug'){d.settings.homepage.projectOrder=d.settings.homepage.projectOrder.map(s=>s===p.slug?String(value):s);for(const c of d.collections){if(c.featuredProject===p.slug)c.featuredProject=String(value);}for(const post of d.journal){if(post.projectSlug===p.slug)post.projectSlug=String(value);}}if(key==='category'){p.categories=Array.from(new Set([value as Category,...(p.categories||[]).filter(c=>c!==p.category)]));}Object.assign(p,{[key]:value});});}
 async function save(){if(!record)return;setBusy(true);setError('');setMessage('');try{const result=await api<{revision:number;data?:SiteContent}>('/api/admin/content',{method:'PUT',body:JSON.stringify(record)});setRecord({...record,revision:result.revision,data:result.data?{...result.data,media:record.data.media}:record.data});setDirty(false);setMessage('Dəyişikliklər saxlanıldı. Saytı yeniləyəndə yeni məzmun görünəcək.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function credentials(e:FormEvent<HTMLFormElement>,login=false){
  e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));setBusy(true);setError('');setMessage('');
  if(!login&&data.password!==data.confirmPassword){setError('Parollar eyni deyil.');setBusy(false);return;}
  try{await api('/api/admin/auth',{method:'POST',body:JSON.stringify({...data,action:login?'login':auth?.configured?'password':'setup'})});form.reset();if(login){await load()}else{setAuth(await api<Auth>('/api/admin/auth'));setMessage('Hesab məlumatları saxlanıldı. Yeni parolunuzla daxil ola bilərsiniz.');}}catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 async function uploadImage(file:File):Promise<string|null>{
  setBusy(true);setError('');setProgress(0);try{const result=await uploadStudioAsset(file,setProgress);edit(d=>{d.media={...d.media,[result.url]:result.asset};const display=result.asset.variants[result.asset.variants.length-1];d.crops[result.url]={width:display.width,height:display.height,bottom:0}});setMessage(result.duplicate?'Eyni fayl arxivdə tapıldı; təkrar saxlanmadı.':'Orijinal və web nüsxələri saxlanıldı.');return result.url;}catch(e){setError((e as Error).message);return null}finally{setBusy(false)}
 }
 async function upload(files:FileList|null){if(!files?.length||!record)return;const target=selected;for(const file of Array.from(files)){const src=await uploadImage(file);if(!src)break;edit(d=>{if(!d.projects[target].images.includes(src))d.projects[target].images.push(src)})}}
 async function replaceImage(file:File,previous:string){const target=selected;const src=await uploadImage(file);if(!src)return;edit(d=>{const project=d.projects[target];project.images=Array.from(new Set(project.images.map(value=>value===previous?src:value)));if(project.coverImage===previous)project.coverImage=src;if(project.heroImage===previous)project.heroImage=src;for(const block of project.blocks||[])for(const item of block.images)if(item.src===previous)item.src=src;})}
 function moveProject(delta:number){const to=selected+delta;if(!record||to<0||to>=record.data.projects.length)return;edit(d=>{[d.projects[selected],d.projects[to]]=[d.projects[to],d.projects[selected]];});setSelected(to);}
 function moveImage(index:number,delta:number){edit(d=>{const images=d.projects[selected].images;const to=index+delta;if(to>=0&&to<images.length)[images[index],images[to]]=[images[to],images[index]];});}
 function removeImage(src:string){edit(d=>{const p=d.projects[selected];const first=p.images[0]===src;p.images=p.images.filter(i=>i!==src);if(p.coverImage===src||(first&&p.coverImage?.endsWith('-thumb.webp')))p.coverImage=p.images[0];if(p.heroImage===src)p.heroImage=p.images[0];if(p.blocks){for(const block of p.blocks){block.images=block.images.filter(image=>image.src!==src);if(block.type==='columns'&&block.images.length===1)block.type='image';}p.blocks=p.blocks.filter(block=>!['image','columns'].includes(block.type)||block.images.length>0);}});}
 function addProject(){if(!record)return;setSearch('');setStatusFilter('all');const index=record.data.projects.length;edit(d=>d.projects.push({id:crypto.randomUUID(),status:'draft',displayPermission:'unreviewed',slug:'project-'+Date.now().toString(36),title:'Yeni layihə',category:'Exterior',type:'',description:'',images:[]}));setSelected(index);}
 function deleteProject(){edit(d=>{d.projects[selected].status='archived'});setConfirm(false);}

 async function logout(){if(dirty){setError('Əvvəl dəyişikliklərinizi saxlayın.');return;}try{await api('/api/admin/auth',{method:'POST',body:JSON.stringify({action:'logout'})});window.location.href='/admin';}catch(e){setError((e as Error).message)}}
 const notice=<div aria-live="polite">{error&&<p className="admin-error" role="alert">{error}</p>}{message&&<p className="admin-success">{message}</p>}</div>;
 if(!auth)return <main id="main" className="admin-shell"><a href="/">← Sayta qayıt</a><h1>Admin</h1>{error?<>{notice}<button className="dark-button" onClick={load}>Yenidən yoxla</button></>:<p>Yüklənir…</p>}</main>;
 if(!auth.authenticated)return <main id="main" className="admin-login"><a className="wordmark" href="/">MIRZAZADA<span>STUDIO</span></a><div className="admin-login-card"><p className="eyebrow">STUDIO / ADMIN</p><h1>İdarəetmə paneli</h1>{auth.configured?<><p>Layihə və renderlərinizi idarə etmək üçün daxil olun.</p><form onSubmit={e=>credentials(e,true)}><label>E-poçt<input name="username" autoComplete="username" required/></label><label>Parol<input type="password" name="password" autoComplete="current-password" required maxLength={128}/></label><button disabled={busy} className="dark-button">{busy?'Yoxlanılır…':'Daxil ol →'}</button></form></>:<p>Supabase-də sahib hesabını qurun.</p>}{notice}<p className="admin-hint">Saytın admin istifadəçisinin e-poçtu və parolu ilə daxil olun.</p><a className="text-link" href="/admin/?recovery=1">Parolu unutdum — Gmail kodu ilə bərpa et →</a><a className="back-link" href="/">← Sayta qayıt</a></div></main>;
 if(!record)return <main id="main" className="admin-shell">{notice}<p>Məzmun yüklənir…</p><button onClick={load}>Yenidən yüklə</button></main>;
 const p=record.data.projects[selected]||record.data.projects[0],s=record.data.settings;
 const imageOptions=Array.from(new Set(record.data.projects.flatMap(p=>p.images)));
 return <ContentProvider data={record.data} allowMediaActions><main id="main" className="admin-shell"><header className="admin-header"><div><a className="wordmark" href="/">MIRZAZADA<span>STUDIO</span></a><p>İdarəetmə paneli</p></div><div className="admin-actions"><a href="/" target="_blank" rel="noreferrer">Sayta bax ↗</a><button type="button" onClick={logout}>Çıxış</button><button className="dark-button" disabled={!dirty||busy} onClick={save}>{busy?'Gözləyin…':dirty?'Dəyişiklikləri saxla':'Yadda saxlanıb ✓'}</button></div></header>{notice}{busy&&<progress className="admin-upload-progress" aria-label="Yükləmə irəliləyişi" max={100} value={progress}/>}
 {!auth.configured&&<p className="admin-banner">Hesab bölməsində öz istifadəçi adınızı və parolunuzu təyin edə bilərsiniz.</p>}
 <fieldset disabled={busy}><Tabs defaultValue="projects"><TabsList className="admin-tabs" variant="line"><TabsTrigger value="projects">Layihələr</TabsTrigger><TabsTrigger value="home">Ana səhifə</TabsTrigger><TabsTrigger value="animation">Animation</TabsTrigger><TabsTrigger value="collections">Kateqoriyalar</TabsTrigger><TabsTrigger value="profile">Haqqımda</TabsTrigger><TabsTrigger value="journal">Blog</TabsTrigger><TabsTrigger value="reviews">Rəylər</TabsTrigger><TabsTrigger value="operations">Müraciətlər / Nüsxələr</TabsTrigger><TabsTrigger value="account">Hesab və parol</TabsTrigger></TabsList>
 <TabsContent value="projects"><div className="admin-workspace"><aside className="admin-project-list"><button className="dark-button" disabled={busy} onClick={addProject}>+ Yeni layihə</button><label className="admin-search">Layihə axtar<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ad və ya kateqoriya"/></label><NativeSelect aria-label="Layihə statusu" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><NativeSelectOption value="all">Hamısı</NativeSelectOption><NativeSelectOption value="draft">Qaralama</NativeSelectOption><NativeSelectOption value="published">Yayımda</NativeSelectOption><NativeSelectOption value="archived">Arxiv</NativeSelectOption></NativeSelect>{record.data.projects.map((project,i)=>({project,i})).filter(({project})=>(statusFilter==='all'||(project.status||'published')===statusFilter)&&(project.title+' '+project.category).toLowerCase().includes(search.toLowerCase())).map(({project,i})=><button key={project.id||i} draggable onDragStart={e=>{setDragged(i);e.dataTransfer.setData('text/plain',project.id||project.slug)}} onDragEnd={()=>setDragged(null)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragged!==null){edit(d=>{const [item]=d.projects.splice(dragged,1);d.projects.splice(i,0,item)});setSelected(i)}setDragged(null)}} className={i===selected?'selected':''} onClick={()=>setSelected(i)}><span>{String(i+1).padStart(2,'0')}</span><div>{project.title}<small>{project.status==='draft'?'Qaralama':project.status==='archived'?'Arxiv':'Yayımda'} · {project.images.length} render</small>{project.updatedAt&&<small>{new Date(project.updatedAt).toLocaleDateString('az-AZ')}</small>}</div></button>)}</aside>
 <section className="admin-editor"><div className="admin-section-heading"><h2>{p.title}</h2><a href={'/projects/'+p.slug} target="_blank" rel="noreferrer">Layihəyə bax ↗</a></div><ProjectDetailsEditor project={p} edit={fn=>edit(d=>fn(d.projects[selected]))}/><div className="admin-editor-actions"><button className="outline-button" onClick={()=>edit(d=>{d.projects[selected].status=p.status==='published'?'draft':'published'})}>{p.status==='published'?'Yayımı dayandır':'Yayıma hazırla'}</button><a href={'/admin/preview/'+p.id} target="_blank" rel="noreferrer">Saxlanmış özəl baxış ↗</a></div><div className="admin-fields"><label>Layihənin adı<input value={p.title} maxLength={150} onChange={e=>projectEdit('title',e.target.value)}/></label><label>Ünvan (slug)<input value={p.slug} maxLength={80} onChange={e=>projectEdit('slug',e.target.value)}/><small>Kiçik latın hərfləri və tire; mövcud link dəyişəcək.</small></label><label>Kateqoriya<NativeSelect value={p.category} onChange={e=>projectEdit('category',e.target.value as Category)}>{projectCategories.map(c=><NativeSelectOption key={c}>{c}</NativeSelectOption>)}</NativeSelect></label><label>Layihə növü<input value={p.type} maxLength={200} onChange={e=>projectEdit('type',e.target.value)}/></label><label className="full">Layihə haqqında<textarea value={p.description} rows={5} maxLength={5000} onChange={e=>projectEdit('description',e.target.value)}/></label></div>
 <div className="admin-category-tags"><p>Əlavə kateqoriyalar</p><div>{projectCategories.filter(category=>category!==p.category).map(category=><button key={category} type="button" aria-pressed={p.categories?.includes(category)||false} onClick={()=>projectEdit('categories',p.categories?.includes(category)?p.categories.filter(c=>c!==category):[...(p.categories||[p.category]),category])}>{p.categories?.includes(category)?'✓ ':''}{category}</button>)}</div><small>Layihə bu filtrlərdə görünür, “All projects” bölməsində yalnız bir dəfə göstərilir.</small></div>
 <div className="admin-category-tags"><p>Sistem və görünüş növləri</p><div>{projectTopics.map(topic=><button key={topic} type="button" aria-pressed={p.topics?.includes(topic)||false} onClick={()=>projectEdit('topics',p.topics?.includes(topic)?p.topics.filter(t=>t!==topic):[...(p.topics||[]),topic])}>{p.topics?.includes(topic)?'✓ ':''}{topic}</button>)}</div><small>Outdoor Systems və Product & Technical səhifələrində əlavə filtrlər yaradır.</small></div>
 <div className="admin-catalog-order"><span>“All projects” sırası: {selected+1} / {record.data.projects.length}</span><button className="outline-button" disabled={selected===0} onClick={()=>moveProject(-1)}>↑ Əvvələ çək</button><button className="outline-button" disabled={selected===record.data.projects.length-1} onClick={()=>moveProject(1)}>↓ Sona çək</button></div>
 <div className="admin-feature"><button aria-pressed={s.homepage.projectOrder.includes(p.slug)} className="outline-button" onClick={()=>edit(d=>{const order=d.settings.homepage.projectOrder;d.settings.homepage.projectOrder=order.includes(p.slug)?order.filter(slug=>slug!==p.slug):[...order,p.slug]})}>{s.homepage.projectOrder.includes(p.slug)?'✓ Ana səhifədə göstərilir':'+ Ana səhifədə göstər'}</button></div>
 <div className="admin-section-heading"><div><h3>Renderlər</h3><p>İlk şəkil əsas görünüşdür. Örtük və lent şəklini ayrıca seçə bilərsiniz.</p></div><label className="admin-upload">+ Render yüklə<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>{void upload(e.target.files);e.target.value=''}}/></label></div>
 {!p.images.length&&<p className="admin-empty">Qaralamanı şəkilsiz saxlamaq olar. Yayımlamaq üçün render əlavə edin.</p>}
 <div className="admin-image-grid">{p.images.map((src,i)=><article key={src}><div className="admin-image-preview"><RenderImage src={src} alt={p.title+' '+(i+1)}/></div><div className="admin-image-actions"><a href={record.data.media?.[src]?.privateOriginal?'/api/admin/assets/'+record.data.media[src].id:src} download aria-label={p.title+' — renderi yüklə'}>Yüklə ↓</a><label className="admin-upload-inline">Əvəz et<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void replaceImage(file,src)}}/></label><button onClick={()=>projectEdit('coverImage',src)} aria-pressed={(p.coverImage||p.images[0])===src}>Örtük</button><button onClick={()=>projectEdit('heroImage',src)} aria-pressed={(p.heroImage||p.images[0])===src}>Ana lent</button><button aria-label="Renderi əvvələ çək" disabled={i===0} onClick={()=>moveImage(i,-1)}>←</button><button aria-label="Renderi sona çək" disabled={i===p.images.length-1} onClick={()=>moveImage(i,1)}>→</button><button onClick={()=>setRemoveTarget(src)}>Çıxar</button></div><label className="admin-crop">Alt hissədən kəs (%)
 <input type="number" min={0} max={35} step={1} value={Math.round((record.data.crops[src]?.bottom||0)*100)} onChange={async e=>{const value=Math.min(35,Math.max(0,Number(e.target.value)))/100;let crop=record.data.crops[src];if(!crop){const image=new Image();image.src=src;await image.decode();crop={width:image.naturalWidth,height:image.naturalHeight,bottom:0};}edit(d=>{d.crops[src]={...crop,bottom:value};if(p.images[0]===src&&p.coverImage?.endsWith('-thumb.webp')&&d.crops[p.coverImage])d.crops[p.coverImage].bottom=value;});}}/></label></article>)}</div>
<BlockEditor project={p} edit={fn=>edit(d=>fn(d.projects[selected]))}/><div className="admin-danger">{p.status==='archived'?<button onClick={()=>edit(d=>{d.projects[selected].status='draft'})}>Arxivdən bərpa et</button>:<button onClick={()=>setConfirm(true)}>Arxivə keçir</button>}<p>Layihə və orijinal fayllar silinmir; arxivdən bərpa edə bilərsiniz.</p></div></section></div></TabsContent>
 <TabsContent value="home"><section className="admin-home-editor"><h2>Ana səhifə və əlaqələr</h2><div className="admin-fields"><label>Başlıq — birinci sətir<input value={s.tagline[0]} onChange={e=>edit(d=>{d.settings.tagline[0]=e.target.value})}/></label><label>Başlıq — ikinci sətir<input value={s.tagline[1]} onChange={e=>edit(d=>{d.settings.tagline[1]=e.target.value})}/></label><label className="full">Giriş mətni<textarea rows={3} value={s.introduction} onChange={e=>edit(d=>{d.settings.introduction=e.target.value})}/></label><label>Studiyanın sahibi<input value={s.founder} onChange={e=>edit(d=>{d.settings.founder=e.target.value})}/></label><label>Animasiya dövrü (saniyə)<input type="number" min={20} max={300} value={s.homepage.cycleSeconds} onChange={e=>edit(d=>{d.settings.homepage.cycleSeconds=Number(e.target.value)})}/></label><label className="full">Studio bölməsinin şəkli<NativeSelect value={s.homepage.studioImage} onChange={e=>edit(d=>{d.settings.homepage.studioImage=e.target.value})}>{imageOptions.map(src=><NativeSelectOption key={src} value={src}>{src.split('/').pop()}</NativeSelectOption>)}</NativeSelect></label></div>
 <h3>Hərəkətli layihələrin sırası</h3><div className="admin-order">{s.homepage.projectOrder.map((slug,i)=><div key={slug}><span>{record.data.projects.find(p=>p.slug===slug)?.title}</span><button disabled={i===0} onClick={()=>edit(d=>{const a=d.settings.homepage.projectOrder;[a[i],a[i-1]]=[a[i-1],a[i]]})} aria-label="Layihəni əvvələ çək">↑</button><button disabled={i===s.homepage.projectOrder.length-1} onClick={()=>edit(d=>{const a=d.settings.homepage.projectOrder;[a[i],a[i+1]]=[a[i+1],a[i]]})} aria-label="Layihəni sona çək">↓</button></div>)}</div><p className="admin-hint">Layihələr bölməsində “Ana səhifədə göstər” düyməsi ilə lentə əlavə edin.</p>
 <h3>Əlaqə məlumatları</h3><div className="admin-fields">{(['email','phone','whatsapp','instagram','instagramUrl','behanceUrl'] as const).map((key,i)=><label key={key}>{['E-poçt','Telefon','WhatsApp — ölkə kodu ilə rəqəmlər','Instagram adı','Instagram — tam https ünvanı','Behance — tam https ünvanı'][i]}<input value={s.contact[key]} onChange={e=>edit(d=>{d.settings.contact[key]=e.target.value})}/></label>)}</div><button className="outline-button" aria-pressed={!s.contact.isPlaceholder} onClick={()=>edit(d=>{d.settings.contact.isPlaceholder=!d.settings.contact.isPlaceholder})}>{s.contact.isPlaceholder?'Nümunə əlaqələr — aktiv et':'✓ Həqiqi əlaqələr aktivdir'}</button>
 <h3>Loqo</h3><label className="admin-upload">Loqo yüklə (PNG/WebP)<input type="file" accept="image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(file){const src=await uploadImage(file);if(src)edit(d=>{d.settings.logoUrl=src})}}}/></label>{s.logoUrl&&<button className="outline-button" onClick={()=>edit(d=>{d.settings.logoUrl=''})}>Mətn loqosuna qayıt</button>}<h3>Xidmətlər</h3>{s.services.map((service,i)=><div className="admin-service" key={i}><label>Xidmət adı<input value={service.title} onChange={e=>edit(d=>{d.settings.services[i].title=e.target.value})}/></label><label>Təsvir<textarea value={service.text} onChange={e=>edit(d=>{d.settings.services[i].text=e.target.value})}/></label><label>Müştəri növü<input value={service.audience||''} onChange={e=>edit(d=>{d.settings.services[i].audience=e.target.value})}/></label><label>Təhvil verilən işlər<textarea value={service.deliverables||''} onChange={e=>edit(d=>{d.settings.services[i].deliverables=e.target.value})}/></label><label>Şəkil<NativeSelect value={service.image} onChange={e=>edit(d=>{d.settings.services[i].image=e.target.value})}>{Array.from(new Set([service.image,...imageOptions])).map(src=><NativeSelectOption key={src} value={src}>{src.split('/').pop()}</NativeSelectOption>)}</NativeSelect></label></div>)}</section></TabsContent>
 <TabsContent value="animation"><AdminAnimation data={record.data} edit={edit} setBusy={setBusy} setError={setError}/></TabsContent>
 <TabsContent value="collections"><CollectionEditor data={record.data} edit={edit}/></TabsContent>
 <TabsContent value="profile"><ProfileEditor data={record.data} edit={edit} uploadImage={uploadImage}/></TabsContent>
 <TabsContent value="journal"><JournalEditor data={record.data} edit={edit} uploadImage={uploadImage}/></TabsContent>
 <TabsContent value="reviews"><ReviewEditor data={record.data} edit={edit}/></TabsContent>
 <TabsContent value="operations"><AdminOperations restore={data=>{edit(current=>Object.assign(current,data));setSelected(0);setSearch('');setStatusFilter('all')}}/></TabsContent>
 <TabsContent value="account"><section className="admin-account"><h2>{auth.configured?'Hesab məlumatlarını dəyiş':'Öz hesabını yarat'}</h2><p>Parol ən azı 12 simvol olmalıdır. Parolun bərpasını Supabase Auth bölməsindən idarə edə bilərsiniz.</p><form onSubmit={credentials}><label>E-poçt<input name="username" defaultValue={auth.username||''} autoComplete="username" minLength={3} maxLength={80} required/></label>{auth.configured&&!auth.owner&&<label>Cari parol<input name="currentPassword" type="password" autoComplete="current-password" required maxLength={128}/></label>}<label>Yeni parol<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label><label>Yeni parolu təkrarla<input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label><button className="dark-button" disabled={busy}>{busy?'Saxlanılır…':'Hesabı saxla'}</button></form></section></TabsContent></Tabs></fieldset>
 <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogTitle>Layihə arxivə keçirilsin?</AlertDialogTitle><AlertDialogDescription>{p.title} açıq saytdan gizlədiləcək, arxivdə saxlanacaq. Bu dəyişiklik “Dəyişiklikləri saxla” düyməsindən sonra sayta tətbiq ediləcək.</AlertDialogDescription><AlertDialogCancel>Ləğv et</AlertDialogCancel><AlertDialogAction onClick={deleteProject}>Arxivə keçir</AlertDialogAction></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!removeTarget} onOpenChange={open=>{if(!open)setRemoveTarget(null)}}><AlertDialogContent><AlertDialogTitle>Render layihədən çıxarılsın?</AlertDialogTitle><AlertDialogDescription>Layihənin bloklarından da çıxarılacaq. Orijinal fayl arxivdə qalır.</AlertDialogDescription><AlertDialogCancel>Ləğv et</AlertDialogCancel><AlertDialogAction onClick={()=>{if(removeTarget)removeImage(removeTarget);setRemoveTarget(null)}}>Renderi çıxar</AlertDialogAction></AlertDialogContent></AlertDialog>
 </main></ContentProvider>;
}
