'use client';
import {useState} from 'react';
import {NativeSelect,NativeSelectOption} from './ui/native-select';
import {RenderImage} from './render-image';
import {hasCategory} from '@/lib/projects';
import type {SiteContent} from '@/lib/content-types';
import type {JournalPost,StudioProfile} from '@/lib/studio-content';
type EditorProps={data:SiteContent;edit:(fn:(data:SiteContent)=>void)=>void};
type MediaProps={uploadImage:(file:File)=>Promise<string|null>};
export function CollectionEditor({data,edit}:EditorProps){return <section className="admin-home-editor"><h2>Kateqoriyaların təqdimatı</h2><p className="admin-hint">Hər bölmə seçilən əsas layihə ilə açılır. Digər layihələr “All projects” sırasını izləyir. Layihələr bölməsində əlavə kateqoriyaları və sistem növlərini seçə bilərsiniz.</p><div className="admin-collection-grid">{data.collections.map((collection,i)=>{const items=data.projects.filter(project=>hasCategory(project,collection.category));const feature=items.find(p=>p.slug===collection.featuredProject)||items[0];return <article key={collection.slug} className="admin-collection-editor">{feature&&<div className="admin-collection-cover"><RenderImage src={feature.coverImage||feature.images[0]} alt={feature.title}/></div>}<div><div className="admin-section-heading"><h3>{collection.category}</h3><a href={'/collections/'+collection.slug} target="_blank" rel="noreferrer">Bax ↗</a></div><p className="admin-hint">{items.length} layihə · {items.reduce((n,p)=>n+p.images.length,0)} render</p><label>Əsas layihə<NativeSelect value={collection.featuredProject} onChange={e=>edit(d=>{d.collections[i].featuredProject=e.target.value})}><NativeSelectOption value="">Sıradakı ilk layihə</NativeSelectOption>{items.map(p=><NativeSelectOption key={p.slug} value={p.slug}>{p.title}</NativeSelectOption>)}</NativeSelect></label><label>Sistem və iş növləri<input value={collection.scope} maxLength={500} onChange={e=>edit(d=>{d.collections[i].scope=e.target.value})}/></label><label>Kateqoriya haqqında<textarea rows={3} value={collection.description} maxLength={2000} onChange={e=>edit(d=>{d.collections[i].description=e.target.value})}/></label></div></article>})}</div></section>;}
export function ProfileEditor({data,edit,uploadImage}:EditorProps&MediaProps){
 const fields:[keyof Omit<StudioProfile,'portrait'>,string,boolean][]=[['role','Peşə başlığı',false],['experience','Təcrübə (məsələn, 12+ years)',false],['location','Şəhər və ölkə',false],['linkedin','LinkedIn profil ünvanı',false],['introduction','Qısa təqdimat',true],['biography','Bioqrafiya — abzasları boş sətirlə ayırın',true],['markets','İşlədiyiniz ölkə və regionlar',true],['expertise','İxtisaslaşma — hər sətirdə bir sahə',true],['education','Təhsil',true],['collaboration','Seçilmiş əməkdaşlıq',true]];
 return <section className="admin-home-editor"><h2>Haqqımda və profil</h2><p className="admin-hint">Bu mətnlər “About” səhifəsində, portret isə həm orada, həm də əlaqə bölməsində göstərilir.</p><div className="admin-profile-media"><RenderImage src={data.profile.portrait} alt={data.settings.founder}/><label className="admin-upload">Portreti dəyiş<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(file){const url=await uploadImage(file);if(url)edit(d=>{d.profile.portrait=url})}}}/></label></div><div className="admin-fields"><label className="full">Ad və soyad<input value={data.settings.founder} maxLength={100} onChange={e=>edit(d=>{d.settings.founder=e.target.value})}/></label>{fields.map(([key,label,multiline])=><label className={multiline?'full':''} key={key}>{label}{multiline?<textarea rows={key==='biography'?6:3} value={data.profile[key]} maxLength={key==='biography'?6000:2000} onChange={e=>edit(d=>{d.profile[key]=e.target.value})}/>:<input value={data.profile[key]} maxLength={key==='linkedin'?300:2000} onChange={e=>edit(d=>{d.profile[key]=e.target.value})}/>}</label>)}</div></section>;
}
export function JournalEditor({data,edit,uploadImage}:EditorProps&MediaProps){
 const [index,setIndex]=useState(0);const post=data.journal[index];
 function update(key:keyof JournalPost,value:string|boolean){edit(d=>{Object.assign(d.journal[index],{[key]:value})})}
 function add(){const next=data.journal.length;edit(d=>d.journal.push({slug:'studio-note-'+Date.now().toString(36),title:'New studio note',excerpt:'',body:'',image:d.projects[0].images[0],topic:'Studio notes',date:new Date().toISOString().slice(0,10),projectSlug:'',published:false}));setIndex(next)}
 const imageOptions=Array.from(new Set([post?.image,...data.projects.flatMap(p=>p.images)].filter(Boolean))) as string[];
 return <section className="admin-home-editor"><div className="admin-section-heading"><h2>Blog yazıları</h2><button className="dark-button" disabled={data.journal.length>=50} onClick={add}>+ Yeni yazı</button></div><p className="admin-hint">Qaralamalar ictimai səhifələrdə göstərilmir. Yazını hazırlayıb “Saytda göstər” seçin və dəyişiklikləri saxlayın.</p><div className="admin-note-list">{data.journal.map((item,i)=><button key={i} aria-pressed={index===i} onClick={()=>setIndex(i)}>{item.title}<small>{item.published?'Yayımda':'Qaralama'}</small></button>)}</div>{post?<><div className="admin-fields"><label>Başlıq<input value={post.title} maxLength={160} onChange={e=>update('title',e.target.value)}/></label><label>Ünvan (slug)<input value={post.slug} maxLength={80} onChange={e=>update('slug',e.target.value)}/></label><label>Mövzu<input value={post.topic} maxLength={80} onChange={e=>update('topic',e.target.value)}/></label><label>Tarix<input type="date" value={post.date} onChange={e=>update('date',e.target.value)}/></label><label className="full">Qısa təsvir<textarea rows={2} value={post.excerpt} maxLength={600} onChange={e=>update('excerpt',e.target.value)}/></label><label className="full">Mətn — abzasları boş sətirlə ayırın<textarea rows={10} value={post.body} maxLength={15000} onChange={e=>update('body',e.target.value)}/></label><label>Əlaqəli layihə<NativeSelect value={post.projectSlug} onChange={e=>update('projectSlug',e.target.value)}><NativeSelectOption value="">Layihə bağlantısı yoxdur</NativeSelectOption>{data.projects.map(p=><NativeSelectOption key={p.slug} value={p.slug}>{p.title}</NativeSelectOption>)}</NativeSelect></label><label>Örtük renderi<NativeSelect value={post.image} onChange={e=>update('image',e.target.value)}>{imageOptions.map(src=><NativeSelectOption key={src} value={src}>{src.split('/').pop()}</NativeSelectOption>)}</NativeSelect></label></div><div className="admin-blog-cover"><RenderImage src={post.image} alt={post.title}/></div><label className="admin-upload">Yeni örtük yüklə<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(file){const target=post.slug,url=await uploadImage(file);if(url)edit(d=>{const p=d.journal.find(item=>item.slug===target);if(p)p.image=url})}}}/></label><div className="admin-editor-actions"><button className="outline-button" aria-pressed={post.published} onClick={()=>update('published',!post.published)}>{post.published?'✓ Saytda göstərilir':'Qaralama — saytda göstər'}</button>{post.published&&<a href={'/blog/'+post.slug} target="_blank" rel="noreferrer">Yazıya bax ↗</a>}<button className="admin-remove" onClick={()=>{edit(d=>{d.journal.splice(index,1)});setIndex(Math.max(0,index-1))}}>Yazını siyahıdan çıxar</button></div></>:<p className="admin-empty">İlk blog yazınızı əlavə edin.</p>}</section>;
}
export function ReviewEditor({data,edit}:EditorProps){return <section className="admin-home-editor"><div className="admin-section-heading"><h2>Müştəri rəyləri</h2><button className="dark-button" disabled={data.testimonials.length>=30} onClick={()=>edit(d=>d.testimonials.push({id:'review-'+Date.now().toString(36),name:'',role:'',quote:'',sample:true,published:false}))}>+ Rəy əlavə et</button></div><p className="admin-hint">Hazır nümunələr real müştəri rəyi deyil və saytda açıq işarələnir. Həqiqi rəyin mətnini, müəllifini və rolunu daxil etdikdən sonra onun statusunu dəyişin.</p>{data.testimonials.map((review,i)=><article className="admin-review-editor" key={review.id}><div className="admin-fields"><label>Rəyin müəllifi<input value={review.name} maxLength={150} onChange={e=>edit(d=>{d.testimonials[i].name=e.target.value})}/></label><label>Şirkət / rol<input value={review.role} maxLength={200} onChange={e=>edit(d=>{d.testimonials[i].role=e.target.value})}/></label><label className="full">Rəy<textarea rows={3} value={review.quote} maxLength={2000} onChange={e=>edit(d=>{d.testimonials[i].quote=e.target.value})}/></label><label>Rəyin növü<NativeSelect value={review.sample?'sample':'real'} onChange={e=>edit(d=>{d.testimonials[i].sample=e.target.value==='sample'})}><NativeSelectOption value="sample">Nümunə — real müştəri rəyi deyil</NativeSelectOption><NativeSelectOption value="real">Müştəridən alınmış həqiqi rəy</NativeSelectOption></NativeSelect></label></div><div className="admin-editor-actions"><button className="outline-button" aria-pressed={review.published} onClick={()=>edit(d=>{d.testimonials[i].published=!d.testimonials[i].published})}>{review.published?'✓ Saytda göstərilir':'Gizlidir — saytda göstər'}</button><button className="admin-remove" onClick={()=>edit(d=>{d.testimonials.splice(i,1)})}>Rəyi siyahıdan çıxar</button></div></article>)}</section>;}
