'use client';
import {fieldText,t} from '@/lib/i18n';
import {ArrowUpRight} from 'lucide-react';
import {RenderImage} from './render-image';
import {useSiteContent} from './content-provider';
import type {JournalPost} from '@/lib/studio-content';
export function JournalCard({post}:{post:JournalPost}){return <a className="journal-card" href={'/blog/'+post.slug}><div className="journal-image">{post.topic==='AI'?<div className="ai-note-art" aria-hidden="true"><span>{t("AI")}</span><small>{t("IDEAS / PROCESS / PERSPECTIVE")}</small></div>:<RenderImage src={post.image} alt={fieldText(post.title,'post:'+post.slug+':title')} loading="lazy"/>}</div><div className="journal-meta"><span>{fieldText(post.topic,'post:'+post.slug+':topic')}</span><span>{t("Studio notes")} <ArrowUpRight size={16}/></span></div><h3>{fieldText(post.title,'post:'+post.slug+':title')}</h3><p>{fieldText(post.excerpt,'post:'+post.slug+':excerpt')}</p></a>;}
export function JournalTeaser(){const {journal}=useSiteContent();const published=journal.filter(post=>post.published&&post.topic!=='AI').slice(0,3);if(!published.length)return null;return <section className="section journal-section"><div className="section-title"><div><p className="eyebrow">{t("04 / STUDIO NOTES")}</p><h2>{t("Behind the perspective.")}</h2></div><a className="text-link" href="/blog">{t("Explore the blog")} <ArrowUpRight size={20}/></a></div><div className="journal-grid">{published.map(post=><JournalCard key={post.slug} post={post}/>)}</div></section>;}
export function Testimonials(){const {testimonials}=useSiteContent();const visible=testimonials.filter(review=>review.published);if(!visible.length)return null;return <section className="section testimonials-section"><div className="section-title"><div><p className="eyebrow">{t("WORKING TOGETHER")}</p><h2>{t("Client perspectives.")}</h2></div>{visible.some(review=>review.sample)&&<p>{t("Sample reviews are labeled below.")}<br/>{t("They illustrate the future review section.")}</p>}</div><div className="testimonials-grid">{visible.map(review=><figure key={review.id} className="testimonial">{review.sample&&<span className="sample-review-badge">{t("SAMPLE · NOT A REAL CLIENT REVIEW")}</span>}<blockquote>“{fieldText(review.quote,'review:'+review.id+':quote')}”</blockquote><figcaption><span>{fieldText(review.name,'review:'+review.id+':name')}</span><small>{fieldText(review.role,'review:'+review.id+':role')}</small></figcaption></figure>)}</div></section>;}

export function AIJournalTeaser(){
 const {journal}=useSiteContent();const notes=journal.filter(post=>post.published&&post.topic==='AI').slice(0,3);
 if(!notes.length)return null;
 return <section className="section ai-notes-section" id="ai-notes"><div className="section-title"><div><p className="eyebrow">{t("AI / STUDIO NOTES")}</p><h2>{t("Ideas beyond the image.")}</h2></div><a className="text-link" href="/collections/ai">{t("Explore AI concepts")} <ArrowUpRight size={19}/></a></div><div className="ai-notes-grid">{notes.map((post,i)=><a className="ai-note-block" href={'/blog/'+post.slug} key={post.slug}><div><span>0{i+1} {t("/ FIELD NOTES")}</span><ArrowUpRight size={23}/></div><h3>{fieldText(post.title,'post:'+post.slug+':title')}</h3><p>{fieldText(post.excerpt,'post:'+post.slug+':excerpt')}</p><span className="ai-read">{t("Read the note →")}</span></a>)}</div></section>;
}
