import {useEffect,useRef,useState,type FormEvent} from 'react';
import {supabase} from './api';
import {RecoveryFlow,recoveryError} from './recovery-flow';
export function PasswordRecovery({fromLink=false}:{fromLink?:boolean}){
 const flow=useRef(new RecoveryFlow(supabase.auth));
 const [step,setStep]=useState<'email'|'code'|'password'|'done'>('email');
 const [email,setEmail]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(fromLink),[error,setError]=useState(''),[message,setMessage]=useState(''),[cooldown,setCooldown]=useState(0);
 useEffect(()=>{if(!fromLink)return;let active=true;void (async()=>{try{await supabase.auth.getSession();await flow.current.acceptLink();if(active)setStep('password');}catch(e){if(active)setError(recoveryError(e));}finally{if(active){setBusy(false);history.replaceState(null,'',location.pathname+'?recovery=1');}}})();return()=>{active=false};},[fromLink]);
 useEffect(()=>{if(!cooldown)return;const timer=setTimeout(()=>setCooldown(value=>Math.max(0,value-1)),1000);return()=>clearTimeout(timer);},[cooldown]);
 async function send(){if(busy||cooldown)return;setBusy(true);setError('');try{await flow.current.send(email,new URL('/admin/',location.origin).href);setStep('code');setCooldown(60);setMessage('Hesab mövcuddursa, bərpa məktubu göndərildi. Gmail-də Inbox və Spam bölmələrini yoxlayın.');}catch(e){setError(recoveryError(e));}finally{setBusy(false)}}
 async function verify(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{await flow.current.verify(email,code);setCode('');setMessage('E-poçt təsdiqləndi. Yeni parol seçin.');setStep('password');}catch(e){setError(recoveryError(e));}finally{setBusy(false)}}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const form=event.currentTarget,values=new FormData(form);setBusy(true);setError('');try{const result=await flow.current.save(String(values.get('password')),String(values.get('confirm')));form.reset();setStep('done');setMessage(result.signedOut?'Parol yeniləndi. Yeni parolunuzla daxil olun.':'Parol yeniləndi. Digər sessiyalardan çıxış təsdiqlənmədi.');}catch(e){setError(recoveryError(e));}finally{setBusy(false)}}
 return <main id="main" className="admin-login"><div className="admin-login-card"><p className="eyebrow">MIRZAZADA STUDIO / ADMIN</p><h1>{step==='done'?'Parol yeniləndi':'Parolu bərpa et'}</h1>
 {step==='email'&&<><p>Saytın admin e-poçtuna təsdiq kodu göndərin.</p><form onSubmit={e=>{e.preventDefault();void send();}}><label>E-poçt<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><button className="dark-button" disabled={busy||cooldown>0}>{busy?'Göndərilir…':'Gmail-ə bərpa kodu göndər →'}</button></form></>}
 {step==='code'&&<><p>{email}</p><form onSubmit={verify}><label>Təsdiq kodu<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6,10}" minLength={6} maxLength={10} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} disabled={busy}/></label><button className="dark-button" disabled={busy}>{busy?'Yoxlanılır…':'Kodu təsdiqlə →'}</button></form><button className="text-link" disabled={busy||cooldown>0} onClick={()=>void send()}>{cooldown?`Yenidən göndər (${cooldown}s)`:'Kodu yenidən göndər'}</button><p className="admin-hint">Məktubda kod əvəzinə yalnız keçid varsa, həmin keçidi açın.</p></>}
 {step==='password'&&<form onSubmit={save}><label>Yeni parol<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required disabled={busy}/></label><label>Yeni parolu təkrarla<input name="confirm" type="password" autoComplete="new-password" minLength={12} maxLength={128} required disabled={busy}/></label><button className="dark-button" disabled={busy}>{busy?'Saxlanılır…':'Yeni parolu saxla →'}</button></form>}
 {error&&<p className="admin-error" role="alert">{error}</p>}{message&&<p role="status" className="admin-hint">{message}</p>}<a className="back-link" href="/admin/">← Admin girişinə qayıt</a></div></main>;
}
